In [34]:
import pandas as pd
import numpy as np

In [37]:
DEFLECTION_PATH = 'initial_data_xlsx_format/load_deflection_data.xlsx'

In [38]:
measurement_df = pd.read_excel(DEFLECTION_PATH)
deflection_df = pd.read_excel(DEFLECTION_PATH, dtype=np.float64)
deflection_df.head()

,Load (P)\n[g],"Deflection (ùúπ)\n[0.001""]","Deflection (ùúπ)\n[0.001""].1","Deflection (ùúπ)\n[0.001""].2","Deflection (ùúπ)\n[0.001""].3","Deflection (ùúπ)\n[0.001""].4","Deflection (ùúπ)\n[0.001""].5","Deflection (ùúπ)\n[0.001""].6","Deflection (ùúπ)\n[0.001""].7","Deflection (ùúπ)\n[0.001""].8","Deflection (ùúπ)\n[0.001""].9","Deflection (ùúπ)\n[0.001""].10","Deflection (ùúπ)\n[0.001""].11","Deflection (ùúπ)\n[0.001""].12","Deflection (ùúπ)\n[0.001""].13","Deflection (ùúπ)\n[0.001""].14"
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,50.0,32.0,15.0,20.0,13.0,14.0,14.0,18.0,13.0,11.0,13.0,17.0,18.0,12.0,19.0,20.0
2,70.0,45.0,20.0,29.0,18.0,20.0,19.0,26.0,20.0,17.0,18.0,23.0,26.0,19.0,27.0,28.0
3,90.0,58.0,25.0,38.0,24.0,27.0,24.0,34.0,27.0,22.0,23.0,31.0,33.0,24.0,34.0,35.0
4,110.0,72.0,30.0,46.0,29.0,33.0,29.0,40.0,32.0,28.0,30.0,38.0,41.0,30.0,42.0,43.0

In [39]:
def convert_thou_mm(df):
    for (column_name, column_data) in df.iteritems():
        if "Deflection" in column_name:
            for i in range(len(column_data.values)):
                column_data.values[i] *= (25.4/1000)
                
    return df

deflection_mm_df = convert_thou_mm(deflection_df)
deflection_mm_df.head()

,Load (P)\n[g],"Deflection (ùúπ)\n[0.001""]","Deflection (ùúπ)\n[0.001""].1","Deflection (ùúπ)\n[0.001""].2","Deflection (ùúπ)\n[0.001""].3","Deflection (ùúπ)\n[0.001""].4","Deflection (ùúπ)\n[0.001""].5","Deflection (ùúπ)\n[0.001""].6","Deflection (ùúπ)\n[0.001""].7","Deflection (ùúπ)\n[0.001""].8","Deflection (ùúπ)\n[0.001""].9","Deflection (ùúπ)\n[0.001""].10","Deflection (ùúπ)\n[0.001""].11","Deflection (ùúπ)\n[0.001""].12","Deflection (ùúπ)\n[0.001""].13","Deflection (ùúπ)\n[0.001""].14"
0,0.0,0.0000,0.000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1,50.0,0.8128,0.381,0.5080,0.3302,0.3556,0.3556,0.4572,0.3302,0.2794,0.3302,0.4318,0.4572,0.3048,0.4826,0.5080
2,70.0,1.1430,0.508,0.7366,0.4572,0.5080,0.4826,0.6604,0.5080,0.4318,0.4572,0.5842,0.6604,0.4826,0.6858,0.7112
3,90.0,1.4732,0.635,0.9652,0.6096,0.6858,0.6096,0.8636,0.6858,0.5588,0.5842,0.7874,0.8382,0.6096,0.8636,0.8890
4,110.0,1.8288,0.762,1.1684,0.7366,0.8382,0.7366,1.0160,0.8128,0.7112,0.7620,0.9652,1.0414,0.7620,1.0668,1.0922

In [40]:
deflection_mm_df.to_excel("deflection_mm.xlsx")

In [42]:
MEASUREMENT_PATH = 'initial_data_xlsx_format/measurement_data.xlsx'
measurement_df = pd.read_excel(MEASUREMENT_PATH)
measurement_df.head()

,Unnamed: 0,Sample 1,Sample 2,Sample 3,Sample 4,Sample 5,Sample 6,Sample 7,Sample 8,Sample 9,Sample 10,Sample 11,Sample 12,Sample 13,Sample 14,Sample 15
0,Length (L)\n[mm],300.00,299.00,299.00,300.00,300.00,299.00,300.00,300.00,299.00,299.00,300.00,300.00,300.00,300.00,300.00
1,Width (b)\n[mm],29.85,30.04,30.14,30.20,30.21,30.21,30.03,30.13,30.10,30.24,30.06,30.06,30.06,30.06,30.12
2,Thickness (h)\n[mm],3.28,3.31,3.27,3.26,3.29,3.28,3.32,3.34,3.35,3.32,3.30,3.35,3.33,3.31,3.29
3,Mass (m)\n[g],3.00,6.00,5.00,7.00,5.00,6.00,4.00,6.00,6.00,6.00,5.00,5.00,6.00,5.00,5.00

In [43]:
def get_density_g_cm3(df):
    densities = []
    for (column_name, column_data) in df.iteritems():
        if "Sample" in column_name:
            # convert to cm and find volume
            this_volume = column_data[0]/10*column_data[1]/10*column_data[2]/10
            # find density in g/cm3
            this_density = column_data[3] / this_volume
            densities.append(this_density)
                
    return densities
densities = get_density_g_cm3(measurement_df)
np.mean(densities)

0.17874673764375407

In [44]:
densities_df = pd.DataFrame(densities).T
densities_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0.102137,0.201814,0.169671,0.237002,0.167688,0.202514,0.133735,0.19874,0.199007,0.199876,0.168014,0.165506,0.199801,0.167507,0.168189

In [45]:
densities_df.to_excel("densities.xlsx")

# TODO
- Get slope of lines
- Get span

In [46]:
# n/mm
slopes = [
    0.5817, 1.4123, 0.9365, 
    1.4787, 1.2917, 1.4947, 
    1.0891, 1.3298, 1.4674, 
    1.4073, 1.1547, 1.0555, 
    1.4442, 1.0476, 1.021,
]
# mm
span = 250

b = [
     29.85, 30.04, 30.14, 
     30.20, 30.21, 30.21, 
     30.03, 30.13, 30.10, 
     30.24, 30.06, 30.06, 
     30.06, 30.06, 30.12,
    ]

h = [
    3.28, 3.31, 3.27, 
    3.26, 3.29, 3.28, 
    3.32, 3.34, 3.35, 
    3.32, 3.30, 3.35, 
    3.33, 3.31, 3.29,
]


print('slopes', len(slopes))
print('b', len(b))
print('h', len(h))

slopes 15
b 15
h 15

In [47]:
def get_youngs_modulus(slopes, b, h, span):
    all_modulus = []
    
    for i in range(len(slopes)):
        this_modulus = (slopes[i] * (span ** 3)) / (4*b[i]*h[i]**3)/1000
        all_modulus.append(this_modulus)
        
    return all_modulus

In [48]:
all_modulus = get_youngs_modulus(slopes, b, h, span)

for i in range(len(all_modulus)):
    all_modulus[i] = round(all_modulus[i], 4)

In [49]:
all_modulus

[2.1572,
 5.0641,
 3.4712,
 5.5205,
 4.6901,
 5.477,
 3.8713,
 4.6271,
 5.0653,
 4.9676,
 4.1754,
 3.6483,
 5.0824,
 3.7539,
 3.7183]

In [50]:
len(all_modulus)

15

In [51]:
rupture_forces_n = [
                    13.78, 35.32, 22.68, 
                    36.73, 31.17, 33.58, 
                    25.13, 35.52, 36.94, 
                    39.03, 28.72, 26.51, 
                    36.67, 25.57, 27.07,
                    ]

In [52]:
def get_rupture_stress(rupture_forces_N, span, b, h):
    all_strength = []
    
    for i in range(len(slopes)):
        this_strength = ( 3*rupture_forces_N[i]*span)/ (2*b[i]*(h[i]**2))
        all_strength.append(round(this_strength, 4))
        
    return all_strength

In [53]:
ultimate_strengths = get_rupture_stress(rupture_forces_n, span, b, h)
print(ultimate_strengths)

[16.0912, 40.2435, 26.3898, 42.9151, 35.7458, 38.7448, 28.4703, 39.6289, 41.0083, 43.9109, 32.9002, 29.4688, 41.2539, 29.115, 31.1367]

In [55]:
modulus_df = pd.DataFrame(all_modulus).T
modulus_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,2.1572,5.0641,3.4712,5.5205,4.6901,5.477,3.8713,4.6271,5.0653,4.9676,4.1754,3.6483,5.0824,3.7539,3.7183

In [57]:
ultimate_strengths_df = pd.DataFrame(ultimate_strengths).T
ultimate_strengths_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,16.0912,40.2435,26.3898,42.9151,35.7458,38.7448,28.4703,39.6289,41.0083,43.9109,32.9002,29.4688,41.2539,29.115,31.1367